In [7]:
from sklearn.datasets import fetch_california_housing
housing = fetch_california_housing()

In [48]:
housing.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [ ]:
housing.feature_names

In [49]:
import pandas as pd

In [55]:
housing_df = pd.DataFrame(housing.data, columns=housing.feature_names)
housing_df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [56]:
housing_df.shape[0]

20640

In [12]:
from sklearn.linear_model import LinearRegression

In [ ]:
X = housing.data
y = housing.target
lr = LinearRegression()
lr.fit(X, y)

In [ ]:
housing_df.()

In [ ]:
target_column_name = ""

Index(['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup',
       'Latitude', 'Longitude'],
      dtype='object')

In [58]:
pred = lr.predict(X)

/Users/a1/Programming/Python/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

In [19]:
lr = LinearRegression()
lr.fit(X, y)import pandas as pd

In [35]:
target_df = pd.DataFrame(housing.target, columns=['target'])
pred_df = pd.DataFrame(pred, columns=["pred"])
pd.concat([target_df, pred_df], axis=1)

       target      pred
0       4.526  4.131650
1       3.585  3.976606
2       3.521  3.676571
3       3.413  3.241598
4       3.422  2.413587
...       ...       ...
20635   0.781  0.133656
20636   0.771  0.553528
20637   0.923  0.171251
20638   0.847  0.319105
20639   0.894  0.515804

[20640 rows x 2 columns]

In [42]:
difference_df = pd.DataFrame(target_df["target"] - pred_df["pred"], columns=["difference"])
difference_df

       difference
0        0.394350
1       -0.391606
2       -0.155571
3        0.171402
4        1.008413
...           ...
20635    0.647344
20636    0.217472
20637    0.751749
20638    0.527895
20639    0.378196

[20640 rows x 1 columns]

In [25]:
from typing import List, Union
def concat_show_all(*dfs: pd.DataFrame) -> pd.DataFrame:
  res_df = pd.concat(list(dfs), axis=1)
  with pd.option_context('display.max_columns', None):
    sample_df = res_df.sample(n=5)

  return sample_df

In [43]:
concat_show_all(target_df, pred_df, difference_df)

       target      pred  difference
3743    3.647  1.700014    1.946986
9931    1.397  1.541544   -0.144544
18084   3.808  3.398440    0.409560
17014   3.881  3.075739    0.805261
15908   2.799  2.766146    0.032854

In [44]:
pd.concat(list([target_df, pred_df, difference_df]), axis=1)

       target      pred  difference
0       4.526  4.131650    0.394350
1       3.585  3.976606   -0.391606
2       3.521  3.676571   -0.155571
3       3.413  3.241598    0.171402
4       3.422  2.413587    1.008413
...       ...       ...         ...
20635   0.781  0.133656    0.647344
20636   0.771  0.553528    0.217472
20637   0.923  0.171251    0.751749
20638   0.847  0.319105    0.527895
20639   0.894  0.515804    0.378196

[20640 rows x 3 columns]

In [45]:
pred_df["difference"] = target_df["target"] - pred_df["pred"]
pred_df

           pred  difference
0      4.131650    0.394350
1      3.976606   -0.391606
2      3.676571   -0.155571
3      3.241598    0.171402
4      2.413587    1.008413
...         ...         ...
20635  0.133656    0.647344
20636  0.553528    0.217472
20637  0.171251    0.751749
20638  0.319105    0.527895
20639  0.515804    0.378196

[20640 rows x 2 columns]

In [46]:
pred_df["difference"].sum() / pred_df.shape[0]

np.float64(-7.843510509475835e-15)